import test from 'node:test';
import assert from 'node:assert/strict';
import {loadSource} from './load-source.mjs';
import {sqliteD1} from './helpers/ai-v2-sqlite.mjs';
import {createHash} from 'node:crypto';
async function setup(){const db=sqliteD1();db.sqlite.exec('CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT,role TEXT); CREATE TABLE sessions(token_hash TEXT,user_id TEXT,expires_at INTEGER);');for(const role of ['member','admin']){db.sqlite.prepare('INSERT INTO users VALUES(?,?,?)').run(role,`${role}@example.invalid`,role);db.sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(`synthetic-${role}`).digest('base64'),role,Date.now()+600000);}const bindings={DB:db,LOCAL_ADMIN_MODE:'false',AI_PROVIDER_ENCRYPTION_KEY:'synthetic-test'};return {bindings,admin:await loadSource('lib/server/ai/admin.ts',bindings)};}
const req=(headers={},body)=>new Request('https://app.invalid/api/admin/ai-providers',{method:body===undefined?'GET':'POST',headers,body});
test('guest, member and forged host cannot manage; legitimate administrator may read',async()=>{const {admin}=await setup();for(const [headers,status] of [[{},401],[{Cookie:'zhiti_session=synthetic-member'},403],[{'X-Forwarded-Host':'localhost',Host:'localhost'},401],[{Cookie:'zhiti_session=synthetic-admin'},200]]){const response=await admin.handle(req(headers),false,async()=>({ok:true}));assert.equal(response.status,status);if(status!==200)assert.equal((await response.json()).error.code,status===401?'UNAUTHORIZED':'FORBIDDEN');}});
test('malformed, cross-scheme and cross-origin writes return stable 403 rather than 500',async()=>{const {admin}=await setup();for(const origin of ['null','not a url','http://app.invalid','https://evil.invalid']){const response=await admin.handle(req({Cookie:'zhiti_session=synthetic-admin',Origin:origin,'Content-Type':'application/json'},'{}'),true,async()=>({ok:true}));assert.equal(response.status,403);assert.equal((await response.json()).error.code,'FORBIDDEN');}});
test('body type, JSON syntax and bounded sizes produce client errors',async()=>{const {admin}=await setup();for(const [body,type,status] of [['{','application/json',400],['[]','application/json',400],['{}','text/plain',400],['{"x":"'+'x'.repeat(65000)+'"}','application/json',413]]){const r=req({Cookie:'zhiti_session=synthetic-admin','Content-Type':type,Origin:'https://app.invalid'},body);const response=await admin.handle(r,true,async()=>admin.jsonBody(r));assert.equal(response.status,status);}});
test('all management endpoints invoke backend administrator gate, including probes and diagnostics',async()=>{const {bindings}=await setup();for(const path of ['app/api/admin/ai-providers/route.ts','app/api/admin/ai-providers/[id]/route.ts','app/api/admin/ai-providers/[id]/models/route.ts','app/api/admin/ai-providers/[id]/models/discover/route.ts','app/api/admin/ai-providers/[id]/test/route.ts','app/api/admin/ai-providers/[id]/diagnostics/route.ts','app/api/admin/ai-routing/route.ts']){const module=await loadSource(path,bindings);for(const [method,fn] of Object.entries(module)){if(!['GET','POST','PATCH','DELETE','PUT'].includes(method))continue;const request=new Request('https://app.invalid/api/admin/ai-providers',{method,headers:{Cookie:'zhiti_session=synthetic-member','Content-Type':'application/json'},...(method==='GET'?{}:{body:'{}'})});const r=await fn(request,{params:Promise.resolve({id:'missing'})});assert.equal(r.status,403,`${method} ${path}`);}}});
