'use client';
import {useState} from 'react';
import type {ProviderConfig,ProviderDiagnostic,WireProtocol} from '../../../../lib/ai-provider-types';
import {PROTOCOL_LABELS} from '../../../../lib/ai-provider-presets';
import {time} from './common';
import css from '../ai-center.module.css';
const names={catalog:'模型目录',text:'文本生成',vision:'图片输入',structured:'结构化输出',task:'业务调用'};
export function ConnectionTestPanel({provider,records,busy,testBusy,test,cancel}:{provider:ProviderConfig;records:ProviderDiagnostic[];busy:boolean;testBusy:boolean;test:(body:unknown)=>void;cancel:()=>void}) {
 const [model,setModel]=useState(provider.models[0]?.id||''),[kind,setKind]=useState('structured'),[protocol,setProtocol]=useState<WireProtocol>(provider.wireApi==='auto'?'responses':provider.wireApi),[consent,setConsent]=useState(false);
 return <section><h2>连接诊断</h2><p className={css.hint}>每次模型测试仅 1 次合成请求，输出上限 512 tokens，不使用学生材料。目录、文本、图片和结构化测试互不代替。</p><div className={css.probeStates}>{(['catalog','text','vision','structured'] as const).map(k=>{const d=records.find(d=>d.kind===k&&!d.stale&&(k==='catalog'||d.modelId===model&&d.protocol===protocol));return <div key={k}><small>{names[k]}</small><strong>{d?(d.code==='OK'?'样本通过':'未通过'):'未测试'}</strong><small>{d?time(d.createdAt):'没有当前配置的记录'}</small></div>;})}</div><fieldset disabled={busy}><div className={css.fields}><label>测试模型<select aria-label="测试模型" value={model} onChange={e=>setModel(e.target.value)}><option value="">请选择模型</option>{provider.models.map(m=><option key={m.id} value={m.id}>{m.id}</option>)}</select></label><label>测试项目<select aria-label="测试项目" value={kind} onChange={e=>setKind(e.target.value)}><option value="text">文本生成</option><option value="vision">图片输入（合成像素）</option><option value="structured">简单 JSON 结构</option></select></label><label>测试协议<select aria-label="测试协议" value={protocol} onChange={e=>setProtocol(e.target.value as WireProtocol)}>{(provider.wireApi==='auto'?['responses','chat_completions']:[provider.wireApi]).map(p=><option key={p} value={p}>{PROTOCOL_LABELS[p as WireProtocol]}</option>)}</select></label></div><label className={css.check}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我同意发送合成样本，并了解测试可能计费</label></fieldset><div className={css.actions}><button data-primary disabled={busy||!model||!consent} onClick={()=>test({modelId:model,kind,protocol,consent})}>{testBusy?'测试中…':'测试模型'}</button>{testBusy&&<button onClick={cancel}>取消测试</button>}</div><p className={css.hint}>通过不等于复杂题库 schema、识别质量或整个提供方均通过。</p><h3>最近记录</h3>{!records.length&&<p className={css.empty}>尚无记录；没有运行的项目不会标为成功。</p>}{records.map(d=><article key={d.id} className={css.record}><strong>{names[d.kind]} · {d.code==='OK'?'样本通过':d.code}{d.stale?' · 已失效':''}</strong><p>{d.modelId||'目录'} · {d.protocol} · HTTP {d.status} · {d.latencyMs}ms · {d.attempts} 次网关尝试 / 上层第 {d.upperAttempt||1} 次{d.fallbackUsed?' · 使用备用':''}</p><code>{d.endpoint}</code><small>{time(d.createdAt)} · 配置 v{d.providerRevision} / 凭据 v{d.credentialRevision}</small></article>)}</section>;
}
