'use client';
import type {AiRoutingConfig,AiTaskRole,ModelTarget,ProviderConfig} from '../../../../lib/ai-provider-types';
import css from '../ai-center.module.css';
const titles:Record<AiTaskRole,string>={recognition:'截图 / 文件识题、答案转录',text:'文字优化 / 解析',diagram:'几何图重绘',grading:'作业批改'};
const encode=(t:ModelTarget|null)=>t?JSON.stringify(t):'';
export function TaskRouting({routing,providers,change,busy}:{routing:AiRoutingConfig;providers:ProviderConfig[];change:(v:AiRoutingConfig)=>void;busy:boolean}) {
 const select=(label:string,value:ModelTarget|null,update:(t:ModelTarget|null)=>void)=><label>{label}<select aria-label={label} value={encode(value)} onChange={e=>update(e.target.value?JSON.parse(e.target.value):null)}><option value="">未设置 / 使用默认</option>{providers.map(p=><optgroup key={p.id} label={`${p.name}${p.enabled?'':'（停用）'}`}>{p.models.map(m=><option key={m.id} value={encode({providerId:p.id,modelId:m.id})}>{m.id}</option>)}</optgroup>)}</select></label>;
 return <section><h2>任务分配</h2><p className={css.hint}>显式主目标 → 按实际输入选默认文本 / 图片目标 → 经允许的环境配置。损坏或停用的显式目标不会被绕过。</p><fieldset disabled={busy}><div className={css.fields}>{select('默认文本目标',routing.defaultTextTarget,t=>change({...routing,defaultTextTarget:t}))}{select('默认图片目标',routing.defaultVisionTarget,t=>change({...routing,defaultVisionTarget:t}))}</div>{routing.routes.map(r=><article className={css.route} key={r.role}><h3>{titles[r.role]}</h3><p className={css.hint}>{r.role==='diagram'?'原题图片 → 矢量结构，需要图片能力。':'按实际是否附图检查能力；不会丢图后交给纯文本模型。'}</p><div className={css.fields}>{select(`${titles[r.role]}主目标`,r.primary,t=>change({...routing,routes:routing.routes.map(x=>x.role===r.role?{...x,primary:t}:x)}))}{select(`${titles[r.role]}备用`,r.fallback,t=>change({...routing,routes:routing.routes.map(x=>x.role===r.role?{...x,fallback:t}:x)}))}</div><label className={css.check}><input type="checkbox" checked={r.fallbackEnabled} onChange={e=>change({...routing,routes:routing.routes.map(x=>x.role===r.role?{...x,fallbackEnabled:e.target.checked}:x)})}/>允许使用此备用目标，并同意向其发送题目与图片</label>{r.fallbackEnabled&&<p className={css.warning}>服务失败或空正文时可能额外计费。鉴权、限流、拒绝、截断及不确定的网络失败不会触发备用。</p>}</article>)}<label className={css.check}><input type="checkbox" checked={routing.allowEnvironmentFallback} onChange={e=>change({...routing,allowEnvironmentFallback:e.target.checked})}/>主目标与对应默认目标均未设置时，允许使用服务器环境配置</label><p className={css.hint}>单次网关最多 3 次上游尝试、最多 2 个提供方，共用截止时间。上层工作流保留独立、有界的重试与断点恢复。</p></fieldset></section>;
}
